- omxplayer.cpp
@popcornmix bdd69f6 breaks 'setvideopos' and 'unhidevideo' by re-asigning bool 'm_new_win_pos' for a different task. 
This commit creates bool 'm_chapter_seek' and changes bool 'm_new_win_pos' back to its original task of disabling seek osd messages only.
> Bugfix: dbus 'setvideopos' and 'unhidevideo'

- OMXPlayerVideo.cpp
- OMXPlayerVideo.h
- omxplayer.cpp
This is a small optimization to the loop logic so that it doesn't do a full close and open of the video player component when looping to the start of a video.
Currently when a video loops back to the start the entire ffmpeg DLL is unloaded and reloaded, the GPU decoder logic is torn down and recreated again, and the decoding threading is destroyed and recreated.  This causes a noticeable delay and blanking of the screen which makes seamless looping impossible.
This change is to add a reset function to the video player component so that it can just do a minimal reset of the internal state back into what's necessary for playing video.  In particular it skips the DLL unload & load, GPU teardown & setup, etc.  The result is that looping happens much quicker and is nearly seamless.  There's …
> Reduce delay and visual stuttering with looping

- omxplayer.cpp
This fixes a bug with the hide & unhide video actions, #313.  The issue is that hide will close the video player component and unhide will cause a seek which expects the video player to be re-opened.  However an optimization was made to seek so that it wouldn't close and re-open the video player (#322), and this ends up breaking unhide.
As a fix this change catches the case where unhide occurs and does an explicit re-open of the video player.  For all other seeks (like looping, user initiated seek, etc.) the quick reset occurs instead of a full close & open.
I tested this by playing a video and using the dbuscontrol.sh to run hide, unhide, and setvideopos.  Before the fix hide would work but neither unhide or setvideopos would work as expected.  After the fix the same commands work as …
> Fix #313 by catching when unhide occurs and explicitly re-opening video player

- OMXPlayerVideo.cpp
- OMXPlayerVideo.h
- omxplayer.cpp
Allows the video layer to be moved, resized, hidden and unhidden without the need to go through the expensive close/open file sequence.
> DBUS: Implement 'non-stutter' setvideopos, hidevideo & unhidevideo

- omxplayer.cpp
This helps wrappers scripts figure out what happened.  Also, tools like
mps-youtube will try a different stream quality on error.
> Normal exit status on user quit or playback end

- .gitignore
- prepare-native-raspbian.sh
Repost of #352 because I forgot to create a separate branch
prepare-native-raspbian.sh no longer uses sudo privileges and especially does not modify the system
in any way. Actions like package installs must now be done explicitly by the user.
ToDo: get rid of prepare-native-raspbian.sh and instead use the standard Debian packaging system
> prepare-native-raspbian.sh: complete overhaul

- omxplayer.cpp
When looping video, omxplayer seeks back to the initial position 2-3 seconds early (this behaviour is seen in 74aac3). I can see there is another pull request claiming to resolve the same issue - I'm not sure if their way is better.
Here is a video that can be used to demonstrate the problem: http://divinelegy.com/wasteland/GenRun/%d0%20is%20for%20%d0ogecoin.mp4
All I have done is moved the loop logic to _after_ EOS is submitted. This seems to let the remaining video play out. I'm not sure if this is wise or not, but it seems to work.
> Play entire video before looping.

- KeyConfig.h
- OMXControl.cpp
- OMXPlayerVideo.cpp
- OMXPlayerVideo.h
- OMXVideo.cpp
- OMXVideo.h
- README.md
- dbuscontrol.sh
- omxplayer.cpp
This patch adds a new option to control the aspect mode.
It supports three modes:
- `letterbox`, which adds black borders to fit the video into the display area without cropping or stretching;
- `fill`, which crops the video to fill the whole display area without stretching;
- `stretch`, which stretches the video to fill the whole display area without cropping.
The default is `letterbox` if the `win` parameter is not used, `stretch` otherwise. This is the same behaviour as it was before this patch.
The patch also adds a way to control cropping of the video (enhancing and superseding #374).
Cheers,
Vittorio
> Allow aspect mode to be configured.

- OMXControl.cpp
- OMXThread.cpp
- omxplayer.cpp
- utils/SingleLock.h
With these fixes omxplayer successfully runs on FreeBSD. It fixes two issues on this OS: 
- Bug fixed in OMXThread.cpp was a crash bug, mutex attribute is actually opaque memory structure on freebsd, so use before initialization was referencing some random memory
- Bug in utils/SingleLock.h caused random deadlock and random crashes for the same reason. Copy of CCriticalSection destroys pthread_mutex_t, freeing the memory it uses and whenever it's reused behavior is undefined
Minor cleanup of linux/fb.h header is just to cleanup code and reduce number of patches in port
> pthread-related bugfixes and minor cross-platform cleanup

- OMXControl.cpp
- OMXReader.h
- README.md
- dbuscontrol.sh
Adds a DBUS operation "GetSource" to the server and to the console client:
dbuscontrol.sh getsource
OMXReader's m_filename has been exposed via «std::string getFilename() const».
Fixes #365
> DBUS: Add operation GetSource returning currently played file/stream

- omxplayer.cpp
Several error conditions exit now with non-zero.
Specific messages are shown for concrete bad argument errors.
Fixes #387.
> Improve return values in main()

- OMXControl.cpp
Do not dispatch messages as the message handling is based on
manually reading the message queue. Fixes #406.
> Fix spurious error replies to D-Bus requests

- DllAvFormat.h
- OMXReader.cpp
- OMXReader.h
- README.md
- omxplayer.cpp
omxplayer on Raspberry Pi is slow to open low-throughput streams. I had this issue when playing mpeg2ts clear QAM streams directly via `/dev/dvb/adapter0/dvr0`, where sometimes it would take around 20 seconds to start playing. It doesn't have to take that long. I traced the cause down to the default `probesize` value of 5000000 in `ffmpeg/libavformat/options_table.h`. By reducing the value to 250000, libavformat is still able to probe the format, but it only takes about 1 second to load. Rather than introduce an omxplayer option to set `probesize` specifically, this patch allows passing a multi-option string to `av_set_options_string`, which should allow setting any number of options defined in `options_table.h`. I chose the name 'lavfdopts` for consistency with `mplayer`.
> Add new option "--lavfdopts" for passing key:value options to libavformat.

- DllAvUtil.h
- OMXReader.cpp
- OMXReader.h
- README.md
- omxplayer.cpp
As discussed in huceke/omxplayer#242
> Add new option "--avdict" for passing key:value options to demuxer

- omxplayer
The omxplayer wrapper script tests for the existence of $OMXPLAYER_DIR/ffmpeg_compiled, and adds it to OMXPLAYER_LIBS if found, which is apparently for local testing. But the actual .so files are in $OMXPLAYER_DIR/ffmpeg_compiled/usr/local/lib.
> omxplayer: Use complete library path under ffmpeg_compiled for local testing.

- Makefile
Fixes inconsistent ownership when installing files. The owner should be
the user installing the files rather than the original owner.
> Makefile: do not preserve ownership when installing libraries

- OMXReader.cpp
This one-liner adds 2 protocols that are supported by ffmpeg,
https://www.ffmpeg.org/ffmpeg-protocols.html#tcp
https://www.ffmpeg.org/ffmpeg-protocols.html#unix
tcp:// works great, and saves me a lot of awful workarounds like creating temporary fifos for omxplayer when playing from a raw tcp stream source.
There is problem with unix://, namely that connect() fails because of the size ffmpeg is passing, but that is a problem to be fixed at the ffmpeg or RPi kernel layer, so I think its Ok to add it here.
> Allow opening "tcp://" and "unix://" URLs.

- Makefile
OMXPlayer calls functions in the vchostif library so it needs to be
explicitly linked otherwise linking errors may occur when vchostif
is built as a shared library instead of a static library.
> Makefile: Explicitly link with vchostif library

- dbuscontrol.sh
dbuscontrol.sh :
- Use root if no user connected, may appear if the bash is called at the boot process.
omxplayer :
- Fix : Dbus fork not reused across batch calls, a new instance is created at each execution.
- Fix : Error "pgrep does not support -F option"
> Bash files bugs fixed

- omxplayer.cpp
> Fix for --no-keys aborting omxplayer when D-Bus connection fails

- KeyConfig.cpp
Broken by 'Improved DBus support' commit.
Keyboard input Pause/Resume function is replaced by KeyConfig::ACTION_PLAYPAUSE.
> Fix for key(board) input pause ('p'/space) didn't paused/resumed player.

- prepare-native-raspbian.sh
The recently added ALSA support requires the libasound2-dev package to
be able to compile on a Jessy based Raspbian.
This fixes the following compile error:
~~~~~
linux/OMXAlsa.cpp:21:28: fatal error: alsa/asoundlib.h: No such file or directory compilation terminated.
Makefile:46: recipe for target 'linux/OMXAlsa.o' failed
make: *** [linux/OMXAlsa.o] Error 1
~~~~~
Fixes: c84083d15cbd ("Initial alsa support")
> Add libasound2-dev as required package

- OMXPlayerSubtitles.cpp
- OMXPlayerSubtitles.h
- SubtitleRenderer.cpp
- SubtitleRenderer.h
- omxplayer.cpp
With this change subtitles and status texts are resized to scale and moved to follow video, when omxplayer is started with the --win option or is resized via dbus setvideopos command.
Previous behavior was: when video was resized, subtitles stayed the same size, as if the video was still in fullscreen.
This is particularly useful in windowed GUI omxplayer wrappers such as KenT2/tboplayer
> Subtitle scaling with video size

- dbuscontrol.sh
This behavior is already correctly implemented for the other "dbuscontrol.sh" commands, when "dbus-send" fails. I'm re-using the existing error handling code.
> bugfix: "dbuscontrol.sh getsource" to return exit code 1 on error

- linux/OMXAlsa.cpp
Fix issue #612 mp3 files play at 2x or 4x the speed.
> Resample embedded samplerate to rate nearest of the target device.

- COPYING
This change updates the gpl mailing address to the current one [1], which fixes the following error from rpmlint:
```
omxplayer.armv7hl: E: incorrect-fsf-address /usr/share/licenses/omxplayer/COPYING
```
[1] https://www.gnu.org/licenses/gpl-2.0.html
> fix GPL mailing address

- omxplayer
It seems omxplayer has made it to FreeBSD, and I did not intend to make it harder for our *BSD friends with a previous pull request.
https://www.freshports.org/multimedia/omxplayer
This PR is a more portable solution to #671 that is compatible with *BSD's.
My apologies for missing this the first time.
> redirect which stderror to /dev/null

- OMXReader.cpp
FFmpeg 4.0 no longer accepts 0 (zero) as an EOF indication, but requires the wrapper to return AVERROR_EOF.
> Fix FFmpeg 4.0 causes omxplayer to hang-up at the end. (#637)
